CREATE DATABASE DB_PIZZARIA_LEGAL; 

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CADASTRO VARCHAR(255),
ENDERECO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255),
PRECO DOUBLE,
TAMANHO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

SELECT * FROM TB_CATEGORIAS;
SELECT * FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS (CADASTRO, ENDERECO) VALUE ("SIM", "RUA PARIS");
INSERT INTO TB_CATEGORIAS (CADASTRO, ENDERECO) VALUE ("SIM", "RUA PORTUGAL");
INSERT INTO TB_CATEGORIAS (CADASTRO, ENDERECO) VALUE ("NÃO", "RUA DAS LARANJEIRAS");
INSERT INTO TB_CATEGORIAS (CADASTRO, ENDERECO) VALUE ("SIM", "AVENIDA CORIFEU");
INSERT INTO TB_CATEGORIAS (CADASTRO, ENDERECO) VALUE ("NÃO", "RUA DAS MARGARIDAS");

INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("MUSSARELA", 50.00, "GRANDE", 1, 1);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("BROCOLIS", 35.00, "BROTO", 1, 2);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("MARGUERITA", 65.00, "GRANDE", 1, 3);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("CALABRESA", 32.00, "BROTO", 1, 4);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("CAMARÃO", 70.00, "GRANDE", 1, 5);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("MORANGO", 30.00, "BROTO", 2, 1);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("BACON", 55.00, "GRANDE", 3, 2);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("PORTUGUESA", 34.00, "BROTO", 1, 3);
INSERT INTO TB_PIZZAS (SABOR, PRECO, TAMANHO, QUANTIDADE, CATEGORIAS_ID) VALUE ("BAURU", 60.00, "GRANDE", 1, 4);

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;

SELECT * FROM TB_PIZZAS WHERE PRECO >= 50 AND PRECO <= 100;

SELECT * FROM TB_PIZZAS WHERE TB_PIZZAS.SABOR LIKE "M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID; /* QUALQUER COISA */

select tb_pizzas.sabor, tb_categorias.cadastro, tb_categorias.endereco from tb_pizzas 
inner join tb_categorias on tb_categorias.id = tb_pizzas.categorias_id where tb_categorias.cadastro = "sim";
