CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT,
CADASTRO VARCHAR(255),
PAGAMENTO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DOUBLE,
CONTROLADO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTO;

INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "DEBITO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "CREDITO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("NÃO", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("NÃO", "DEBITO");

INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("ESCITALOPRAM", 100.00, "SIM", 1, 1);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("FRALDA", 35.00, "NÃO", 1, 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("LEITE EM PÓ", 25.00, "NÃO", 1, 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("DORFLEX", 12.00, "NÃO", 2, 4);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("DIPIRONA", 8.00, "NÃO", 1, 5);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("MIRTAZAPINA", 100.00, "SIM", 2, 1);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("POMADA", 30.00, "NÃO", 3, 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("VITAMINAC", 10.00, "NÃO", 3, 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUE ("CREMEDECABELO", 30.00, "NÃO", 2, 4);

SELECT * FROM TB_PRODUTO WHERE PRECO > 50.00;

SELECT * FROM TB_PRODUTO WHERE PRECO >= 50 AND PRECO <= 60;

SELECT * FROM TB_PRODUTO WHERE TB_PRODUTO.NOME LIKE "C%";

SELECT * FROM TB_PRODUTO INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PRODUTO.CATEGORIA_ID;

select tb_produto.nome, tb_categoria.cadastro, tb_categoria.pagamento from tb_produto 
inner join tb_categoria on tb_categoria.id = tb_produto.categoria_id where tb_categoria.pagamento = "DINHEIRO";
