CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;

USE DB_CIDADE_DOS_VEGETAIS;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT,
CPF VARCHAR(255),
PAGAMENTO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DOUBLE,
PESO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTO;

INSERT INTO TB_CATEGORIA (CPF, PAGAMENTO) VALUE ("SIM", "DEBITO");
INSERT INTO TB_CATEGORIA (CPF, PAGAMENTO) VALUE ("SIM", "CREDITO");
INSERT INTO TB_CATEGORIA (CPF, PAGAMENTO) VALUE ("SIM", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CPF, PAGAMENTO) VALUE ("SIM", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CPF, PAGAMENTO) VALUE ("SIM", "DEBITO");

INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("MELANCIA", 150.00, "5KG", 1, 1);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("CARAMBOLA", 5.00, "1KG", 1, 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("MAÇA", 10.00, "2KG", 1, 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("ALFACE", 60.00, "1", 2, 4);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("TOMATE", 8.00, "1KG", 1, 5);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("ABACAXI", 6.00, "1", 2, 1);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("BROCOLIS", 70.00, "1", 3, 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("LIMÃO", 50.0, "10KG", 3, 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, PESO, QUANTIDADE, CATEGORIA_ID) VALUE ("PERA", 30.00, "5KG", 2, 4);

SELECT * FROM TB_PRODUTO WHERE PRECO > 50.00;

SELECT * FROM TB_PRODUTO WHERE PRECO >= 50 AND PRECO <= 150;

SELECT * FROM TB_PRODUTO WHERE TB_PRODUTO.NOME LIKE "C%";

SELECT * FROM TB_PRODUTO INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PRODUTO.CATEGORIA_ID;

select tb_produto.nome, tb_categoria.cpf, tb_categoria.pagamento from tb_produto 
inner join tb_categoria on tb_categoria.id = tb_produto.categoria_id where tb_categoria.cpf = "SIM";
